export const ITEM_ADD_TO_CART = 'ITEM_ADD_TO_CART';
export const ITEM_REMOVE_FROM_CART_ONE = 'ITEM_REMOVE_FROM_CART_ONE';

export const CART_REMOVE_ALL = 'CART_REMOVE_ALL';

export const ITEM_REMOVE_FROM_CART = 'ITEM_REMOVE_FROM_CART'
